Twistd working

diff --git a/marcopolo/daemon/systemv/marcod b/marcopolo/daemon/systemv/marcod
--- a/marcopolo/daemon/systemv/marcod
+++ b/marcopolo/daemon/systemv/marcod
@@ -1,4 +1,5 @@
-#! /bin/sh
+#!/bin/sh
+
 ### BEGIN INIT INFO
 # Provides:          marcod
 # Required-Start:    $remote_fs $syslog
@@ -13,19 +14,30 @@
 # Author: Diego Martin <martinarroyo@usal.es>
 #
 
+#FROM: https://twistedmatrix.com/trac/attachment/ticket/3434/twistdplugin
+
 # Do NOT "set -e"
 
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin/
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+TWISTED_NAME="marcod"
 DESC="The marcopolo discoverer"
-NAME=marcod
-DAEMON=/usr/local/bin/$NAME
-DAEMON_ARGS=
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+DAEMON=/usr/bin/twistd
+SERVICE_NAME="/etc/marcopolo/daemon/marco_twistd.tac"
+#SERVICE_DIR=/home/user/twistedplugin
 
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+PIDFILE=/var/run/marcopolo/${TWISTED_NAME}.pid
+LOGFILE=/var/log/marcopolo/${TWISTED_NAME}-twistd.log
+
+DAEMON_OPTS="--pidfile=$PIDFILE --logfile=$LOGFILE -y $SERVICE_NAME"
+
+# Set python path so twistd can find the plugin
+# See: http://twistedmatrix.com/projects/core/documentation/howto/plugin.html
+#export PYTHONPATH=$SERVICE_DIR
+
+if [ ! -x $DAEMON ]; then
+  echo "ERROR: Can't execute $DAEMON."
+  exit 1
+fi
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -38,99 +50,53 @@ SCRIPTNAME=/etc/init.d/$NAME
 # and status_of_proc is working.
 . /lib/lsb/init-functions
 
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+start_service() {
+  echo -n " * Starting $SERVICE_NAME... "
+  start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
+  e=$?
+  if [ $e -eq 1 ]; then
+    echo "already running"
+    return
+  fi
+
+  if [ $e -eq 255 ]; then
+    echo "couldn't start :("
+    return
+  fi
+
+  echo "done"
 }
 
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
-}
+stop_service() {
+  echo -n " * Stopping $SERVICE_NAME... "
+  start-stop-daemon -Kq -R 10 -p $PIDFILE
+  e=$?
+  if [ $e -eq 1 ]; then
+    echo "not running"
+    return
+  fi
 
+  echo "done"
+}
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
+    start_service
+    ;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-	;;
-  
+    stop_service
+    ;;
   restart)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-		# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+    stop_service
+    start_service
+    ;;
+  status)
+    status_of_proc "$DAEMON" "$TWISTED_NAME" && exit 0 || exit $?
+    ;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
+    echo "Usage: /etc/init.d/$SERVICE_NAME {start|stop|restart|status}" >&2
+    exit 1   
+    ;;
 esac
 
-:
+exit 0
